config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :prospect_forms, only: [:index, :show, :new, :create]

  resources :propositions, only: [:show, :new, :create]


  resources :etablissements, only: [:index, :show, :new, :create]
  get 'initiate_database', to: 'etablissements#initiate_database', as: 'initiate_database'
  get 'initiate_price_and_services_database', to: 'etablissements#initiate_price_and_services_database', as: 'initiate_prices_db'
  get 'success', to: 'prospects#success', as: 'success'
  get 'mentions-légales', to: 'pages#mentions_légales', as: 'mentions'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'qui-sommes-nous', to: 'pages#qui_sommes_nous', as: 'qui_sommes_nous'


end

app/controllers/prospect_forms_controller.rb
class ProspectFormsController < ApplicationController

  def new
    @prospect_form = ProspectForm.new
  end

  def create
    cleaned_params = clean_array_params(prospect_form_params)
    @prospect_form = ProspectForm.new(cleaned_params)
    if @prospect_form.save
      
      # Créer une Proposition après la création réussie d'un ProspectForm
      Proposition.create_for_prospect_form(@prospect_form)
      redirect_to root_path
    else
      render :new
    end
  end


  def index
    @prospect_forms = ProspectForm.all
  end

  def show
    @prospect_form = ProspectForm.find(params[:id])
    @etablissements_proches = Etablissement.near([@prospect_form.latitude_de_recherche, @prospect_form.longitude_de_recherche], @prospect_form.rayon_de_recherche).limit(7)
    if @etablissements_proches.empty?
      @etablissements_proches = Etablissement.near([@prospect_form.latitude_de_recherche, @prospect_form.longitude_de_recherche], @prospect_form.rayon_de_recherche + 10)
    else
      @etablissements_proches
    end
  end

  private

  def prospect_form_params
    params.require(:prospect_form).permit(
      :email, :telephone, :adresse_de_recherche, :rayon_de_recherche,
      :nombre_de_places, :connaissance_gir, :echelle_gir, :etat_de_sante,
      :conditions_medicales_particulieres, :maladie_degenerative,
      :fréquence_des_visites, :etat_du_dossier_administratif,
      :budget_mensuel, :commentaires,
      :type_de_chambre,
      :animal_de_compagnie,
      :connaissance_gir,
      :revenu_mensuel_mini,
      :echelle_gir,
      :temps_de_trajet_maximum_en_minutes,
      :moyen_de_transport,
      :routing_preference,
      transit_option:[],
      services_indispensables: [],
      services_souhaites: [],
      type_de_residence: [],
      confession_de_la_residence: [],
      interets_pour_sorties: [],
      interets_pour_activites: [],
      besoins_alimentaires: [],
      meubles_et_objets_personnels: [],
      besoins_spécifiques_aménagement: [],
      besoins_spécifiques_visiteurs: [],
      aides_financieres_déjà_obtenues_ou_en_cours: [],
      aides_financieres_a_demander: []
    )
  end



  def clean_array_params(params)
    array_attributes = [
      :services_indispensables,
      :services_souhaites,
      :type_de_residence,
      :confession_de_la_residence,
      :interets_pour_sorties,
      :interets_pour_activites,
      :besoins_alimentaires,
      :besoins_spécifiques_aménagement,
      :besoins_spécifiques_visiteurs,
      :aides_financieres_déjà_obtenues_ou_en_cours,
      :aides_financieres_a_demander,
      :transit_option,
      :meubles_et_objets_personnels
    ]
    array_attributes.each do |attribute|
      params[attribute]&.reject!(&:blank?)
    end
    params
  end

end

app/views/prospect_forms/index.html.erb
<% @prospect_forms.each do |prospect| %>
  <div class="greener-card">
  <p><strong>Demande crée le :</strong></p><%= prospect.created_at.strftime("%d/%m/%Y à %H:%M") %>
  <p> <strong>Mail de contact</strong></p>
  <%= prospect.email %>
  <p><strong>Numéro de téléphone</strong></p>
  <%= prospect.telephone %>
  <p><strong>Message:</strong></p>
  <%= prospect.commentaires %>
    <% if prospect.proposition.present? %>
      <%= link_to 'Voir Proposition', proposition_path(prospect.proposition) %>
    <% end %>
  </div>
<%  end  %>

app/views/prospect_forms/new.html.erb
<div class="container">
  <%= simple_form_for @prospect_form do |f| %>

    <h3 class="quizz-part-title text-center pt-5">Contact</h3>
    <!-- Informations de contact du demandeur -->
    <div class="green-card">
      <%= f.input :email, as: :email %>
      <%= f.input :telephone %>
    </div>

    <h3 class="quizz-part-title text-center">Critères géographiques</h3>
    <!-- Critère géographique -->
    <div class="green-card">
      <%= f.input :adresse_de_recherche, label: 'Lieu de recherche', input_html: {data: { target: "address-autocomplete.adresseDeRecherche", address_autocomplete_target: ":adresse_de_recherche"}, class:"d-none" },
                  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>

      <!-- Demander si c'est la même ville? -->
      <%= f.input :rayon_de_recherche, as: :radio_buttons, collection: ['1 km', '3 km','5 km', '10 km', '20 km', '50 km', '100 km'], default: '100 km' %>
      <%= f.input :temps_de_trajet_maximum_en_minutes, label:'Temps de trajet maximum depuis l\'adresse indiquée', as: :radio_buttons, collection: ['10 minutes', '20 minutes', '30 minutes', '40 minutes', '50 minutes', '60 minutes', 'Supérieur à 1h'] %>

      <div data-controller="transport">
        <%= f.input :moyen_de_transport, label: 'En:', as: :radio_buttons, collection: ['Voiture', 'Transports en commun', 'Marche à pied'],
                    input_html: {data: {transport_target: "transportType", action: "transport#change"}} %>

        <div data-transport-target="transitOption" class="d-none">
          <%= f.input :transit_option, label: 'Avez-vous une préférence pour un moyen de transport en commun ?', as: :check_boxes, collection: ['Bus', 'Train/Tramway/metro', 'Sans préférence'] %>
        </div>

        <div data-transport-target="routingPreference" class="d-none">
          <%= f.input :routing_preference, label: 'Avez-vous une préférence ?', as: :radio_buttons, collection: ['Le moins de marche à pied', 'Le moins de changements', 'Sans préference'] %>
        </div>
      </div>

    </div>

    <h3 class="quizz-part-title text-center">Critères concernant l'établissement</h3>
    <!-- Etablissement -->
    <div class="green-card">
      <%= f.input :nombre_de_places, as: :radio_buttons, collection: [1,2] %>
      <%= f.input :services_indispensables, as: :check_boxes, collection: ['Soins médicaux', 'Activités', 'Sorties', 'Accueil de jour'] %>
      <%= f.input :services_souhaites, label:"Services souhaités", as: :check_boxes, collection: ['Piscine', 'Jardin', 'Salon de coiffure', 'Restaurant'] %>
      <%= f.input :type_de_residence,label:"Type de résidence", as: :check_boxes, collection: ['Autonome', 'Semi-autonome', 'Non-autonome'] %>
      <%= f.input :confession_de_la_residence, label:"Confession de la résidence", as: :check_boxes, collection: ['Catholique', 'Protestante', 'Juive', 'Musulmane', 'Non confessionnelle'] %>
      <%= f.input :interets_pour_sorties,label:"Intérêts pour les sorties", as: :check_boxes, collection: ['Culturelles', 'Récréatives', 'Shopping', 'Nature'] %>
      <%= f.input :interets_pour_activites,label:"Intérêts pour les activités", as: :check_boxes, collection: ['Peinture', 'Jardinage', 'Lecture', 'Jeux de société'] %>
    </div>

    <h3 class="quizz-part-title text-center">Critères de confort</h3>
    <!-- Confort individuel -->
    <div class="green-card">
      <%= f.input :type_de_chambre,as: :radio_buttons, collection: ['Individuelle', 'Double', 'Suite', 'Sans préférence'] %>
      <%= f.input :animal_de_compagnie,as: :radio_buttons, collection: ['Oui', 'Non'] %>
      <%= f.input :besoins_alimentaires, as: :check_boxes, collection: ['Sans sel', 'Sans sucre', 'Végétarien', 'Végétalien'] %>
      <%= f.input :meubles_et_objets_personnels, as: :radio_buttons, collection: ['Oui', 'Non'], default: 'Non' %>
    <%= f.input :besoins_spécifiques_aménagement,label:"Aménagements spécifiques", as: :check_boxes,  collection: ['Accès fauteuil roulant', 'Barres d’appui', 'Lit médicalisé'] %>
    </div>

    <!-- Critères médicaux -->
    <h3 class="quizz-part-title text-center">Critères médicaux</h3>
    <div class="green-card" data-controller="connaissance-gir">
      <%= f.input :connaissance_gir, as: :radio_buttons, collection: [['Oui', true], ['Non', false]], label: "L'évaluation GIR a-t-elle été réalisée ?", input_html: { data: { connaissance_gir_target: "knowsGir", action: "connaissance-gir#toggleGirVisibility" } } %>

      <div id="gir_selection" style="display:none;" data-connaissance-gir-target="girSelection">
        <%= f.input :echelle_gir,label:"Échelle GIR", as: :radio_buttons, collection: ['GIR 1-2', 'GIR 3-4', 'GIR 5-6'] %>
      </div>

      <div id="gir_description" style="display:none;" data-connaissance-gir-target="girDescription">
        <%= f.input :echelle_gir,
          label:"Quelle description se rapproche le plus de l'état de la personne?",
          collection: [
            ['Personne encore autonome dans les actes de la vie courante', 'GIR 5-6'],
            ['Personne ayant seulement besoin d\'une aide ponctuelle pour la toilette, la préparation des repas et le ménage', 'GIR 5-6'],
            ['Personne n\'assumant pas ses transferts mais qui une fois levée peut se déplacer à l\'intérieur de son logement et a besoin d\'aide pour la toilette et l\'habillage ou personne n\'ayant pas de problèmes locomoteurs mais qui doit être aidée pour les soins corporels et les repas', 'GIR 3-4'],
            ['Personne ayant conservé son autonomie mentale, partiellement son autonomie locomotrice, mais qui a besoin quotidiennement et plusieurs fois par jour d\'une aide pour les soins corporels', 'GIR 3-4'],
            ['Personne confinée au lit ou au fauteuil, dont les fonctions mentales ne sont pas totalement altérées et dont l\'état exige une prise en charge pour la plupart des activités de la vie courante, ou personne dont les fonctions mentales sont altérées, mais qui est capable de se déplacer et qui nécessite une surveillance permanente', 'GIR 1-2'],
            ['Personne confinée au lit ou au fauteuil dont les fonctions mentales sont gravement altérées et qui nécessite une présence indispensable et continue d\'intervenants', 'GIR 1-2'],
            ['Je ne sais pas']
          ],
          as: :radio_buttons,
          label_method: :first,
          value_method: :last
        %>
      </div>

      <%= f.input :etat_de_sante,label: "État de santé",  as: :radio_buttons,  collection: ['Présence infirmière permanente', 'Présence médicale permanente', 'Présence infirmière quotidienne','Présence médicale quotidienne','Présence médicale hebdomadaire'] %>
      <%= f.input :conditions_medicales_particulieres, label: "Conditions médicales particulières (besoins de consulter des médecins spécialisés...)"%>
      <%= f.input :maladie_degenerative,label:"Maladie dégénérative",  as: :radio_buttons, collection: ['Oui', 'Non'] %>
    </div>

    <!-- Critères des visites -->
    <h3 class="quizz-part-title text-center">Critères des visites</h3>
    <div class="green-card">
      <%= f.input :fréquence_des_visites, as: :radio_buttons, collection: ['Quotidiennes', 'Hebdomadaires', 'Mensuelles','Pas de visiteur'] %>
      <%= f.input :besoins_spécifiques_visiteurs,  as: :check_boxes, collection: ['Accès handicapé', 'Parking', 'Horaires flexibles'] %>
    </div>

    <!-- Critères administratifs -->
    <h3 class="quizz-part-title text-center">Critères administratifs</h3>
    <div class="green-card">
      <%= f.input :etat_du_dossier_administratif,label:"État du dossier administratif", as: :radio_buttons, collection: ['Complet', 'Incomplet', 'Non commencé'] %>
      <%= f.input :revenu_mensuel_mini, label: "La personne a un revenu mensuel inférieur à 2 635,54 € ", as: :boolean %>
      <%= f.input :budget_mensuel,label:"Budget mensuel maximum", collection: 1000.step(5000, 500) %>
      <%= f.input :aides_financieres_déjà_obtenues_ou_en_cours,label:"Aides financières déjà obtenues ou en cours",as: :check_boxes, collection: ['APA', 'Aide sociale', 'PCH', 'CAF', 'Ne sais pas'] %>
      <%= f.input :aides_financieres_a_demander,label:"Aides financières à demander",as: :check_boxes, collection: ['APA', 'Aide sociale', 'PCH', 'CAF', 'Ne sais pas'] %>
      <%= f.input :commentaires %>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.button :submit , "Suivant", class:"btn btn-yellow mb-5 px-5" %>
    </div>
  <% end %>
</div>

app/views/prospect_forms/show.html.erb
<%= link_to 'Back', prospect_form_path %>

<div class="container">
<div class="greener-card">
  <h2> Informations de Contact</h2>
  <%= @prospect_form.email %>

  <%= @prospect_form.telephone %>

  <%= @prospect_form.revenu_mensuel_mini  %>

<h3>Date de la fiche</h3>
  <%= @prospect_form.created_at %>
</div>

</div>

<h3>Etablissements proches</h3>
<% @etablissements_proches.each do |e|  %>
<div class="greener-card">
<p><strong><%= e.raison_sociale %></strong></p>
<p>Adresse: <%= e.adresse%></p>
<p>Téléphone: <%= e.telephone%></p>
<% if @prospect_form.revenu_mensuel_mini %>
<p>Prix minimum: <%= e.prix_minimum %></p>
<% else %>
<p>Prix minimum vu la situation de la personne:</p>
<p><%= e.prix_fonction_gir(@prospect_form.echelle_gir)%> €</p>
<% end %>

<%= link_to 'Voir l’Établissement', etablissement_path(e), class:"btn btn-success m-3" %>

</div>
<% end %>

app/views/prospect_forms/succes.html.erb
<div class="greener-card text-center">
<h2>Merci d'avoir pris le temps de remplir ce formulaire</h2>
<p>Notre équipe reviendra vers vous au plus vite pour vous proposer un
accompagnement personnalisé</p>
<p>Nous proposons deux formules, la première axée principalement sur la recherche de l'établissement,
la seconde comprenant également la réalisation de l'ensemble des démarches administratives</p>
<p>Nous insistons sur le fait que nous sommes les seuls à proposer ce service et que nous n'avons
aucun partenariat de quelque sorte que ce soit avec une quelconque maison, nous garantissons notre impartialité.</p>
</div>
<%= link_to 'Retourner à la page d\'accueil', root_path, class:"btn btn-yellow" %>