config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :prospect_forms, only: [:index, :show, :new, :create]

  resources :propositions, only: [:show, :new, :create]


  resources :etablissements, only: [:index, :show, :new, :create]
  get 'initiate_database', to: 'etablissements#initiate_database', as: 'initiate_database'
  get 'initiate_price_and_services_database', to: 'etablissements#initiate_price_and_services_database', as: 'initiate_prices_db'
  get 'success', to: 'prospects#success', as: 'success'
  get 'mentions-légales', to: 'pages#mentions_légales', as: 'mentions'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'qui-sommes-nous', to: 'pages#qui_sommes_nous', as: 'qui_sommes_nous'


end

app/views/shared/_footer.html.erb
<footer>
<%# haut du footer %>
  <div>

  </div>

<%# bas du footer %>
  <div class="footer-green">


  <%= link_to "Accueil", root_path  %>
  <%= link_to "Contact", contact_path %>
  <%=  link_to "Mentions légales", mentions_path %>


  </div>



</footer>

app/views/shared/_navbar.html.erb
    <nav>
      <div class="navbar">
        <div class="container nav-container">
            <input class="checkbox" type="checkbox" name="" id="" />
            <div class="hamburger-lines">
              <span class="line line1"></span>
              <span class="line line2"></span>
              <span class="line line3"></span>
            </div>
          <div class="logo">
            <h1>FacilEhpad</h1>
          </div>
          <div class="menu-items">
          <li><%= link_to "Accueil", root_path %></li>
            <li><%= link_to "Établissements", etablissements_path %></li>
            <li><%= link_to "Demandes", prospect_forms_path %></li>
           <li>  <%= link_to "Remplir une demande", new_prospect_form_path %></li>
           <li><%= link_to "Qui sommes nous? ", qui_sommes_nous_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <%# <li><a href="#">FAQ</a></li> %>
          </div>
        </div>
      </div>
    </nav>

app/views/shared/_navbar_green.html.erb
<nav>
<div class="green_navbar">
<p>FacilEhpad</p>
</div>

</nav>